### PR TITLE
MGMT-12451: Configure CIM

### PR DESCRIPTION
**Pull request by mareklibra**
The feature adds ability to initially configure the Central Infrastructure Management in the Advance cluster management application.

Depends on:
- [x] https://github.com/openshift-assisted/assisted-ui-lib/pull/1761
- [x] https://github.com/openshift-assisted/assisted-ui-lib/pull/1771 (needs new ai-ui-lib 2.7.4-cim release)
- [x] rebased on top of #2264 

Screenshot from 2022-11-29 14-27-29
Screenshot from 2022-11-29 14-27-56
Screenshot from 2022-11-29 14-28-14
Screenshot from 2022-11-29 14-28-27
Screenshot from 2022-11-29 14-30-41
Screenshot from 2022-11-29 14-30-48
Screenshot from 2022-11-29 14-35-39
Screenshot from 2022-11-29 14-39-42

### CODE REVIEW

**Comment by KevinFCormier** [comment]
@mareklibra Can you please fix the spacing between the fields the the "G" unit that appears after them?

Also, are these strings from the assisted-ui-lib? Since they appear in MCE/ACM, I think our docs team should probably review them. In this case I notice the word "now" is redundant in the message. @swopebe do you have someone from docs team assigned to review messages for Assisted Installer / CIM and does this include messages contained in the [assisted-ui-lib repository](https://github.com/openshift-assisted/assisted-ui-lib/blob/master/locales/en/translation.json)?

**Comment by mareklibra** [comment]
@KevinFCormier thanks for the feedback, I will update the spacing.

Recent PR is functional but still WIP - I will update the texts before requesting review.

Anyway, the ai-ui-lib texts (not only those by this PR) are already reviewed/authored by Allison, the content writer. I can share contact off-line if needed. Do we need a second round here?

**Comment by KevinFCormier** [comment]
@mareklibra OK, that's good. Just wanted to confirm a writer is reviewing. Thanks.

**Review by jtomasek — APPROVED** [review]
/lgtm

**Comment by KevinFCormier** [comment]
@mareklibra You added watches for 3 resource types, but the backend needs permission to do this. Currently this should be added in 2 places. (I am hoping to reduce this to just the MCE side soon.)

https://github.com/stolostron/multiclusterhub-operator/blob/main/pkg/templates/charts/toggle/console/templates/console-clusterrole.yaml
https://github.com/stolostron/backplane-operator/blob/main/pkg/templates/charts/toggle/console-mce/templates/console-clusterrole.yaml

**Pull request merged**
