### PR TITLE
Pool test updates

### PR DESCRIPTION
**Pull request by ellajuengst**

### CODE REVIEW

**Comment by ellajuengst** [comment]
Added these changes -- now the test is working! ...except still getting the errors 
```
!!!!!!!!!!!!!!!! MISSING MOCKS !!!!!!!!!!!!!!!!!!!!!!!!
(Make sure the mocks in test match these mocks)
GET /apis/hive.openshift.io/v1/namespaces/test-pool-namespace/clusterclaims/mycluster-test
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

in `should be able to claim a cluster with only standby clusters`, and 

```
!!!!!!!!!!!!!!!! MISSING MOCKS !!!!!!!!!!!!!!!!!!!!!!!!
(Make sure the mocks in test match these mocks)
GET /apis/hive.openshift.io/v1/namespaces/test-pool-namespace/clusterclaims/mycluster-standby
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

in `should be able to claim a cluster and delete pending claim`

**Comment by KevinFCormier** [comment]
Superseded by https://github.com/stolostron/console/pull/1451

**Pull request closed without merging**
