### PR TITLE
restore the fix for 24928

### PR DESCRIPTION
**Pull request by ChunxiAlexLuo**
Signed-off-by: Chunxi Luo chuluo@redhat.com

https://github.com/stolostron/backlog/issues/24928

### CODE REVIEW

**Review by mprahl — APPROVED** [review]

**Comment by ChunxiAlexLuo** [comment]
https://github.com/stolostron/backlog/issues/24928#issuecomment-1218073489

/cc @KevinFCormier @Randy424

**Comment by KevinFCormier** [comment]
@ChunxiAlexLuo FF is to release-2.7, so please cherry-pick to release-2.6

**Pull request merged**
