### PR TITLE
ACM-8257 Fix issue with suggestion selection of marked text

### PR DESCRIPTION
**Pull request by zlayne**
related bug: https://issues.redhat.com/browse/ACM-8257

### CODE REVIEW

**Comment by KevinFCormier** [comment]
@zlayne Did you investigate if this behaves the same for all OCP versions (and therefore PF versions) that we run on? Just wondering if it's always been broken, or something that behaves a little differently depending on PF version.

**Comment by zlayne** [comment]
@KevinFCormier Yes, we have discovered this has been present since the searchbar rewrite (2.7). The issue occurs when the user clicks directly on the marked/highlighted text as seen in the attached image (user clicked in the `Config` in `ConfigMap`).

Using the previous `event.target.innerText` returns the element where the event started. In this case, the innerText is `Config` not `ConfigMap`. (We use the <mark> element)
Using `event.currentTarget.innerText` returns which element the event was attached to or the element whose eventListener triggered the event. So this contains the entire text of the suggestion.

The issue was in how I was handling the JS event, and to my knowledge, the Patternfly version shouldn't matter.

Screenshot 2023-10-24 at 6 46 07 PM

**Comment by KevinFCormier** [comment]
@zlayne Great! Thank you for confirming.

> @KevinFCormier Yes, we have discovered this has been present since the searchbar rewrite (2.7). The issue occurs when the user clicks directly on the marked/highlighted text as seen in the attached image (user clicked in the `Config` in `ConfigMap`).
> 
> Using the previous `event.target.innerText` returns the element where the event started. In this case, the innerText is `Config` not `ConfigMap`. (We use the element) Using `event.currentTarget.innerText` returns which element the event was attached to or the element whose eventListener triggered the event. So this contains the entire text of the suggestion.
> 
> The issue was in how I was handling the JS event, and to my knowledge, the Patternfly version shouldn't matter.
> 
> Screenshot 2023-10-24 at 6 46 07 PM

**Pull request merged**
