### PR TITLE
Add backup labels, fix install config annotation

### PR DESCRIPTION
**Pull request by Randy424**
Signed-off-by: randybrunopiverger <rbrunopi@redhat.com>
https://github.com/open-cluster-management/backlog/issues/18422

### CODE REVIEW

**Comment by Randy424** [comment]
/cc @jamestalton 

...prow seems to want two reviewers?

**Comment by KevinFCormier** [comment]
> /cc @jamestalton
> 
> ...prow seems to want two reviewers?

I think it's just because the Prow config hasn't been updated yet for the org rename.

**Comment by KevinFCormier** [comment]
Merged manually for now.

**Pull request merged**
