### PR TITLE
update moment, nconf via temptifly

### PR DESCRIPTION
**Pull request by RobDolares**
Signed-off-by: rhowingt@redhat.com <rhowingt@redhat.com>

https://github.com/stolostron/backlog/issues/21680
https://github.com/stolostron/backlog/issues/21871

Ran `npm audit fix` to update

Manually updated `temptifly` to bump `nconf` version from `0.11.3` to `0.11.4`

Before
```
@stolostron/console-frontend@0.0.1 
└─┬ temptifly@0.3.60
  └── nconf@0.11.3 
├─┬ @stolostron/ui-components@0.180.2
│ └── moment@2.29.1  deduped
├─┬ @types/moment@2.13.0
│ └── moment@2.29.1  deduped
└── moment@2.29.1 
```

After
```
@stolostron/console-frontend@0.0.1
└─┬ temptifly@0.3.60
  └── nconf@0.11.4 
├─┬ @stolostron/ui-components@0.180.2
│ └── moment@2.29.3  deduped
├─┬ @types/moment@2.13.0
│ └── moment@2.29.3  deduped
└── moment@2.29.3 
```

### CODE REVIEW

**Comment by KevinFCormier** [comment]
I'm not comfortable with updating `temptifly` to the 0.5.z stream... there may be changes we need to deal with.

**Review by jeswanke — APPROVED** [review]

**Pull request merged**
