### PR TITLE
update wizard pkg and submit button for importcluster flow

### PR DESCRIPTION
**Pull request by RobDolares**
Signed-off-by: rhowingt@redhat.com <rhowingt@redhat.com>
related issue: https://github.com/stolostron/backlog/issues/24557

<kbd>Screen Shot 2022-08-03 at 4 28 43 PM</kbd>

### CODE REVIEW

**Review by jeswanke — APPROVED** [review]

**Review by jeswanke — APPROVED** [review]

**Review by jamestalton — APPROVED** [review]
lgtm

**Review by Randy424 — APPROVED** [review]
/lgtm

**Pull request merged**
