### PR TITLE
ACM-11959 - Alter information alert and doc link for Discovery Config page

### PR DESCRIPTION
**Pull request by Randy424**
Regarding [ACM-11959](https://issues.redhat.com/browse/ACM-11959)

Remove unneeded link and update remaining policy example link with URL for new document.

Before:
screenshot_2024-05-29_at_11 35 39___am

After:
Screenshot 2024-06-21 at 11 55 12 AM

### CODE REVIEW

**Comment by Randy424** [comment]
/hold

Waiting for some feedback from Doc team assignee

**Review by robdolares — APPROVED** [review]
/lgtm

**Comment by Randy424** [comment]
New changes from Doc [here](https://github.com/stolostron/console/compare/a393ce846cf3f46587f085d7b2d18a172c3e4c19..198589a6184ba94843f254d1d004654833f98d1e)

**Review by robdolares — APPROVED** [review]
/lgtm

**Pull request merged**
