### PR TITLE
update err output when failed get logs

### PR DESCRIPTION
**Pull request by zhiweiyin318**
story: https://issues.redhat.com/browse/ACM-9195

### CODE REVIEW

**Comment by KevinFCormier** [comment]
@zhiweiyin318 Please reach out to the docs team for help with the error string. In addition, it should be set up for translation. I also notice that there was a documentation link included before. Is there a new link we could point to? Ideally, the link should actually be formatted as a link. The logs error is currently stored as a string, but probably we could store it as a ReactNode instead.

**Comment by zhiweiyin318** [comment]
@KevinFCormier thanks the comment. 
The previous link `https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_sfor_kubernetes/2.10/html-single/release_notes/red-hat-advanced-cluster-management-for-kubernetes-release-note#non-ocp-logs` cannot address `non-ocp-logs` page.  Not sure if we still have `non-ocp-logs` page.
And from 2.10, the log function can work on all clusters, so do not need differentiate OCP and non-OCP cluster. But depend on the cluster-proxy and managed-serviceaccount addons.

@oafischer  could you help review the error string ? thanks
/assign @oafischer

**Review by oafischer — APPROVED** [review]

**Comment by zhiweiyin318** [comment]
Thanks @KevinFCormier for helping update the PR. I appreciate it so much.

**Review by zlayne — APPROVED** [review]

**Pull request merged**
