### PR TITLE
Fix app table crashing with RBAC user

### PR DESCRIPTION
**Pull request by fxiang1**
issues: 
- https://github.com/stolostron/backlog/issues/20984
- https://github.com/stolostron/backlog/issues/20982

Changes
- Removed dependency on managedCluster recoilstate as only admin users can list those
- Fix cluster status showing warning when its green
- Fix Argo editor link
- Display namespace instead of destination namespace for AppSet on app table

### CODE REVIEW

**Review by chenz4027 — DISMISSED** [review]
Thanks Feng for the quick fix!

**Comment by fxiang1** [comment]
Had to add more fixes. @chenz4027 Can you review again? Thanks.

**Review by chenz4027 — APPROVED** [review]
lgtm!

**Pull request merged**
