### PR TITLE
ACM-5429 ACM-2670 Refactor operator alert

### PR DESCRIPTION
**Pull request by KevinFCormier**
https://issues.redhat.com/browse/ACM-5429
https://issues.redhat.com/browse/ACM-2670

### CODE REVIEW

**Review by fxiang1 — DISMISSED** [review]
Looks great Kevin! Thanks for improving the code!

**Comment by fxiang1** [comment]
Putting on hold in case Randy has any comments.

**Comment by KevinFCormier** [comment]
Thanks @fxiang1. I noticed one more little thing so I pushed another commit. @Randy424 can you review please?

**Review by fxiang1 — APPROVED** [review]

**Review by Randy424 — APPROVED** [review]
/lgtm

**Comment by Randy424** [comment]
Looks good, I reviewed a bit earlier but waited to comment. Thanks!

**Pull request merged**
