### PR TITLE
GRC tables don't expand full width of screen like the rest of ACM tables

### PR DESCRIPTION
**Pull request by ChunxiAlexLuo**
Signed-off-by: Chunxi Luo <chuluo@redhat.com>

https://github.com/stolostron/backlog/issues/25597

`isWidthLimited` is introduced in https://github.com/stolostron/console/pull/1112

@jamestalton @KevinFCormier @RobDolares  let me know if removing `isWidthLimited` will cause any potential issue.

### CODE REVIEW

**Review by RobDolares — DISMISSED** [review]
/lgtm

**Comment by ChunxiAlexLuo** [comment]
The apostrophe in the branch name, close and reopen another PR https://github.com/stolostron/console/pull/2132

**Pull request closed without merging**
