### PR TITLE
[2.6] Bug 2125269: ACM plugin custom extension for row action

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
- For application details page

Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
@KevinFCormier @fxiang1  This PR is a 2.6 cherry-pick of https://github.com/stolostron/console/pull/2016

**Comment by GowthamShanmugam** [comment]
@fxiang1 I used your application details page test PR to backport my 2.6.1 PR.

**Review by fxiang1 — APPROVED** [review]
lgtm

**Pull request merged**
