### PR TITLE
Fix the credential form issues

### PR DESCRIPTION
**Pull request by chenz4027**
Signed-off-by: Maggie Chen <magchen@redhat.com>
https://issues.redhat.com/browse/ACM-1914 

Fix both crash and auto select issues

image

### CODE REVIEW

**Review by KevinFCormier — COMMENTED** [review]
For `<CredentialsForm>` you have a `control` property, which is set to a `setNewSecret` state updater. Would it be possible to simply call this function only after the credential has been successfully created? That way you avoid having to create a new state to track whether creation has failed.

Perhaps this call can be done later in the function, like just before we close the modal in the successful case:
https://github.com/stolostron/console/blob/main/frontend/src/routes/Credentials/CredentialsForm.tsx#L1311

Also, is there a better name we could use for the `control` property?

**Comment by chenz4027** [comment]
Thanks @KevinFCormier , will look into it

**Comment by chenz4027** [comment]
Thanks @KevinFCormier , will fix it

**Review by KevinFCormier — APPROVED** [review]
Thanks for the updates!

**Pull request merged**
