### PR TITLE
Improve or remove messages regarding consumption of cloud resources

### PR DESCRIPTION
**Pull request by KevinFCormier**
Signed-off-by: Kevin Cormier <kcormier@redhat.com>

### CODE REVIEW

**Comment by KevinFCormier** [comment]
@berenss Might need a bit more finessing. One of the messages says that hibernating “blocks all cluster operations” but that is a strange way of putting it to me. Maybe we should still mention that virtual machines are stopped? What do you think.

**Review by berenss — DISMISSED** [review]
Hi Kevin I like this new content. It is succinct, and I think the messaging is safe within the context of what a user should expect.
perhaps using 'management operations' more accurately describes what you mean
> "Moving to the Hibernating state blocks any management operations for the clusters

**Review by berenss — APPROVED** [review]
🚀

**Pull request merged**
