### PR TITLE
ACM-2286 Key ansible templates on index only (same template repeated allowed)

### PR DESCRIPTION
**Pull request by KevinFCormier**
Signed-off-by: Kevin Cormier <kcormier@redhat.com>

### CODE REVIEW

**Comment by KevinFCormier** [comment]
@jeswanke @RobDolares I propose that we override the test coverage requirement for this PR. Many of the uncovered lines are in code that is anticipating future support of scale and destroy operations for the ClusterCurator. That is not currently supported and is disabled.

**Review by RobDolares — APPROVED** [review]
/lgtm

**Pull request merged**
