### PR TITLE
ACM-5044 Fix Template type column width to 30%

### PR DESCRIPTION
**Pull request by KevinFCormier**
https://issues.redhat.com/browse/ACM-5044

### Before
image

image
image

### After

image
image

image

### CODE REVIEW

**Review by Randy424 — APPROVED** [review]
/lgtm

**Comment by KevinFCormier** [comment]
Oops! Fixed the tests. I changed the column header to be singular instead of plural, and the string was referenced in a couple tests.

**Review by Randy424 — APPROVED** [review]
/lgtm

**Pull request merged**
