### PR TITLE
ACM-12426 PatternFly 5 adoption

### PR DESCRIPTION
**Pull request by KevinFCormier**
https://issues.redhat.com/browse/ACM-12426

- Updates patternfly packages to version 5 or compatible version
- Updates codebase with automated codemod and class name changes
- Replaces temporarily copied SearchInput implementation with import
- Wraps icons in Icon component to specify size and status (for standard colors)
- Fixes all event handlers (event is now always the first argument for event callbacks on PF components)
- Introduces AcmHelperText component that sets up form helper text using the new FormHelperText component (attributes for helper text and validated state on FormGroup have been removed)
- Numerous other small updates for PF component API changes
- Styling fixes and bug workarounds
- Updates monaco packages

### CODE REVIEW

**Comment by Randy424** [comment]
Found this on `/multicloud/applications/advanced` while running the environment locally. 
Screenshot 2024-12-05 at 1 18 53 PM

**Comment by KevinFCormier** [comment]
> Found this on `/multicloud/applications/advanced` while running the environment locally. Screenshot 2024-12-05 at 1 18 53 PM

Thanks @Randy424 
I pushed a fix: https://github.com/stolostron/console/pull/3809/commits/aca9b1566947486eb1816b94194b345569aa2dc7

**Review by vishsanghishetty — APPROVED** [review]
/lgtm

**Review by Randy424 — APPROVED** [review]
/lgtm

**Review by jeswanke — COMMENTED** [review]
LGTM

**Pull request merged**
