### PR TITLE
ACM-2666 Added percentage beside hc upgrade status

### PR DESCRIPTION
**Pull request by o-farag**
Previously, the percentage completion when upgrading would not be displayed. Now show upgrade percentage beside the status.
image

### CODE REVIEW

**Comment by o-farag** [comment]
@fxiang1 regarding the security hotspot, is it an issue since the message isn't defined by the user, it's defined in the CR? I could try using string manipulation instead if you think that's better

**Comment by fxiang1** [comment]
@o-farag I think it should be ok since the input is not from users but rather from the API status and I don't believe users can manipulate the API status.

**Review by fxiang1 — APPROVED** [review]
LGTM! Thanks Omar!

**Pull request merged**
