### PR TITLE
Update packages 2.4

### PR DESCRIPTION
**Pull request by KevinFCormier**
https://github.com/stolostron/backlog/issues/19545
https://github.com/stolostron/backlog/issues/19551
https://github.com/stolostron/backlog/issues/19900
https://github.com/stolostron/backlog/issues/19487

**Before**

shelljs 0.8.4
node-fetch 2.6.1
nanoid 3.1.25
follow-redirects 1.14.2

npm uninstall @redhat-cloud-services/rule-components i18next-http-backend @stolostron/ui-components @kubernetes/client-node jest-fetch-mock @types/css-minimizer-webpack-plugin css-loader
npm i -D @redhat-cloud-services/rule-components@^3.2.1 i18next-http-backend@1.3.2 @stolostron/ui-components@~1.25.4 @kubernetes/client-node@^0.15 jest-fetch-mock@^3.0.3 @types/css-minimizer-webpack-plugin@^3.0.2 css-loader@6.3.0
npm audit fix

**After**

shelljs 0.8.5
node-fetch 2.6.7
nanoid 3.3.1
follow-redirects 1.14.8

### CODE REVIEW

**Comment by Randy424** [comment]
@KevinFCormier incidentally, this also contains the fix for https://github.com/stolostron/backlog/issues/19487 (for the 2.4 release anyway). Mind if I close my PR for this branch in favor of yours?

**Comment by KevinFCormier** [comment]
@Randy424 Ah, right... yup, I'll add it to the list of addressed ones. Hopefully streams will open late next week.

**Review by zlayne — APPROVED** [review]

**Pull request merged**
