### PR TITLE
ACM-2914

### PR DESCRIPTION
**Pull request by o-farag**
Fixed issue where clusters with periods in their name would cause console crash on import

Signed-off-by: Omar Farag <ofarag@redhat.com>

### CODE REVIEW

**Review by fxiang1 — CHANGES_REQUESTED** [review]
@o-farag in ACM the namespace for imported clusters must be the same as the cluster name. So I'm afraid we can't modify the namespace to a different value. Can you check the cluster name and display an error instead? ie. validate the cluster name against the suggested regex `[a-z0-9]([-a-z0-9]*[a-z0-9])?`

**Comment by o-farag** [comment]
@fxiang1 I've changed it to that. Do you want something specific? At the moment, clicking import cluster just returns this error message:
image

I could change the error message and/or disable the import cluster dialogue all together instead

**Comment by fxiang1** [comment]
@o-farag Thanks, I think that looks good! I do want to change the error message a bit to specify why the name is invalid.
Maybe we can use:
`The cluster name is invalid. Change the name to the RFC 1123 standard which consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character.`

**Review by fxiang1 — APPROVED** [review]
LGTM! Thanks Omar!

**Pull request merged**
