### PR TITLE
Transpose standards and categories

### PR DESCRIPTION
**Pull request by KevinFCormier**
https://github.com/stolostron/backlog/issues/20777
https://github.com/stolostron/backlog/issues/20709 (singular/plural issue)

### CODE REVIEW

**Review by zlayne — APPROVED** [review]

**Comment by KevinFCormier** [comment]
@zlayne Sorry for the premature review request - missed prettier. Please re-review at your convenience. Thanks!

**Review by jamestalton — APPROVED** [review]
lgtm

**Pull request merged**
