### PR TITLE
Placement bug fix, application wizard

### PR DESCRIPTION
**Pull request by Randy424**
Signed-off-by: randybrunopiverger <rbrunopi@redhat.com>
regarding: https://github.com/stolostron/backlog/issues/21983

Tested cases: 
- Create app, choose git as a repo source, add new placement, change app name (should update placement reference)
- Create app, choose git as a repo source, select an existing placement, change app name (should not update existing placement name)
- Create app, choose git as repo source, select "select an existing placement", combobox should be empty
- Create a multi app subscription with two subscriptions, delete the first subscription, change the placement of the remaining subscription to the placement created for the first subscription.

### CODE REVIEW

**Comment by Randy424** [comment]
@KevinFCormier @jeswanke ready for review, thanks so much!

**Comment by KevinFCormier** [comment]
@Randy424 I found another odd case.

1. Fill out form to create a new application.
2. Select an existing placement rule.
3. Change the name of the app. Placement rule is not affected. Great!
4. Now, clear the existing placement rule by clicking the X in the box. It gets initialized with a generated name based on the new name of the app, but no placement of that name exists.

**Comment by Randy424** [comment]
/hold
working on that issue...

**Review by jeswanke — DISMISSED** [review]

**Review by jeswanke — APPROVED** [review]

**Review by jeswanke — APPROVED** [review]

**Comment by Randy424** [comment]
@jeswanke @chenz4027 I think this needs a lgtm tag too

**Comment by KevinFCormier** [comment]
I think this covers all the cases now. Great work!

**Pull request merged**
