### PR TITLE
Update translation function for informOnly policies

### PR DESCRIPTION
**Pull request by zyjjay**
Quick fix to add missing translation functions

### CODE REVIEW

**Review by mprahl — APPROVED** [review]

**Comment by KevinFCormier** [comment]
@mprahl Sorry I missed this one... not sure why you needed my approval. But the associated issue https://issues.redhat.com/browse/ACM-6879 was closed. Should this PR be closed or merged?

**Comment by yiraeChristineKim** [comment]
@KevinFCormier  Hi Kevin, Let me ask @zyjjay  and I will take care of it. Thanks for your double-check!

**Review by yiraeChristineKim — APPROVED** [review]

**Pull request merged**
