### PR TITLE
Adjust policy compliance statuses

### PR DESCRIPTION
**Pull request by dhaiducek**
- Remove "UnknownCompliancy"
- Add "Inapplicable"

### CODE REVIEW

**Comment by yiraeChristineKim** [comment]
Great! Could you ping me after unit test fixed?

**Comment by dhaiducek** [comment]
What unit test? The tests passed. The failure is Sonarcloud, but both issues it raised are unrelated to this PR.

Backend:
```
 [test:*backend] Test Suites: 16 passed, 16 total
[test:*backend] Tests:       39 passed, 39 total
[test:*backend] Snapshots:   0 total
[test:*backend] Time:        16.78 s
[test:*backend] Ran all test suites.
[test:*backend] npm run test:backend -- --maxWorkers\=2 exited with code 0 
```
Frontend:
```
 [test:*frontend] Test Suites: 1 skipped, 274 passed, 274 of 275 total
[test:*frontend] Tests:       8 skipped, 1685 passed, 1693 total
[test:*frontend] Snapshots:   173 passed, 173 total
[test:*frontend] Time:        578.053 s
[test:*frontend] Ran all test suites.
[test:*frontend] npm run test:frontend -- --maxWorkers\=2 exited with code 0 
```

**Comment by dhaiducek** [comment]
image

**Comment by dhaiducek** [comment]
Should I address these two issues from Sonarcloud?

**Comment by yiraeChristineKim** [comment]
Oh? ci/prow/unit-tests-sonarcloud —  failed to me

**Comment by KevinFCormier** [comment]
@dhaiducek It's up to you. I don't usually bother with the code complexity ones. The component-in-a-component one I would be slightly more inclined to fix, but in either case you can mark them as Accepted in Sonarcloud if you don't intend to fix.

**Comment by yiraeChristineKim** [comment]
no Let's override

**Comment by yiraeChristineKim** [comment]
I can fix it! I am working on PolicyTemplateDetail now

**Comment by dhaiducek** [comment]
Thanks @KevinFCormier and @yiraeChristineKim! Looks like the cognitive complexity one might have been the blocking issue and the re-run might pass since the SonarCloud status turned green. @yiraeChristineKim, I've assigned the component definition issue to you.

**Review by yiraeChristineKim — APPROVED** [review]

**Pull request merged**
