### PR TITLE
ACM-4741 Display upgrade automations

### PR DESCRIPTION
**Pull request by KevinFCormier**
https://issues.redhat.com/browse/ACM-4741

image

### CODE REVIEW

**Comment by KevinFCormier** [comment]
@oafischer @sho Any feedback on the wording for the alert in this modal?

> **Automation templates are configured**
> One or more of the selected clusters have automations that will run before or after the upgrade. Expand the table rows to view the Ansible templates for each cluster.

**Comment by oafischer** [comment]
Looks good to me!

**Review by Randy424 — APPROVED** [review]
/lgtm

**Pull request merged**
