### PR TITLE
ACM-3506 Deprecated for SyncEditor

### PR DESCRIPTION
**Pull request by jeswanke**
Signed-off-by: John Swanke <jswanke@redhat.com>

### CODE REVIEW

**Comment by chenz4027** [comment]
Looking good @jeswanke!
image

Just wondering, would it be possible to add the alert to app sub's subscription that references placementRules where kind='placementrule'? App sub does not display the selected placementRule resource in edit mode.

image

**Comment by KevinFCormier** [comment]
@chenz4027 Are you planning to consume this in Train-02? Should we deliver now?

**Comment by KevinFCormier** [comment]
@chenz4027 Looks like you never approved - I'm not sure if @jeswanke responded to your requests. Is it ready to merge?

**Review by chenz4027 — APPROVED** [review]
/lgtm

**Pull request merged**
