### PR TITLE
Update the operator policy required fields

### PR DESCRIPTION
**Pull request by mprahl**
These fields are no longer required after:
https://issues.redhat.com/browse/ACM-10561

### CODE REVIEW

**Comment by mprahl** [comment]
@dockerymick could you please review the text in this PR?

**Comment by dockerymick** [comment]
@mprahl thanks, will do in the AM

**Review by dockerymick — CHANGES_REQUESTED** [review]

**Comment by mprahl** [comment]
Thanks for the quick review @dockerymick! I addressed your comments. Could you please take another look?

**Review by dockerymick — APPROVED** [review]
Thanks for accepting my suggestions, this looks good

**Review by JustinKuli — APPROVED** [review]

**Review by yiraeChristineKim — APPROVED** [review]

**Pull request merged**
