### PR TITLE
ACM-3892 Error message details

### PR DESCRIPTION
**Pull request by KevinFCormier**
Show detailed error message from backend in alerts and bulk action modal error table.

image

image

### CODE REVIEW

**Comment by KevinFCormier** [comment]
@oafischer Can I get your thoughts on the new message `Expand table rows to view detailed error messages.` as shown in the screenshot of the bulk action modal, please?

**Comment by oafischer** [comment]
Looks good, might even add a "the" before "table rows" since there is a little more space in detailed message like that.

/lgtm

**Review by oafischer — DISMISSED** [review]

**Pull request merged**
