### PR TITLE
Update complianceType for limit range policy

### PR DESCRIPTION
**Pull request by ChunxiAlexLuo**
Signed-off-by: Chunxi Luo chuluo@redhat.com

https://github.com/stolostron/backlog/issues/23677

### CODE REVIEW

**Review by dhaiducek — DISMISSED** [review]
LGTM!
@KevinFCormier Would you prefer the semver caret remain in place?

**Comment by ChunxiAlexLuo** [comment]
> LGTM! @KevinFCormier Would you prefer the semver caret remain in place?

I removed it to prevent updating to 1.8.3, it seems npm doesn't treat 1.8.x as a major update and will automatically bump from 1.7.x to 1.8.x

**Comment by dhaiducek** [comment]
@ChunxiAlexLuo In that case, we'd need `~` for z-streams, but I'll leave it to the Console team to decide whether we need anything there at all.

**Review by dhaiducek — APPROVED** [review]

**Comment by Randy424** [comment]
> @ChunxiAlexLuo In that case, we'd need `~` for z-streams, but I'll leave it to the Console team to decide whether we need anything there at all.

@jamestalton Wondering if you have a strong opinion on this?

**Review by jamestalton — APPROVED** [review]
lgtm

**Pull request merged**
