### PR TITLE
Add provider connection changed to add credential

### PR DESCRIPTION
**Pull request by ellajuengst**
https://github.com/stolostron/backlog/issues/19371

Signed-off-by: Ella Juengst <ellajuengst@gmail.com>

### CODE REVIEW

**Review by KevinFCormier — CHANGES_REQUESTED** [review]
Looks good!

We do not support translation yet, but we are working to get there. You may have noticed we use a mix of symbolic keys for the strings along with the actual strings.

In the interest of improving things, can you please:
1. Remove the old string from `frontend/public/locales/en/plugin__acm-plugin.json`
2. From the `frontend` directory, run `npm run i18n`. This will add your new string to the translation file. It will also sort the strings, so you will see a bunch of changes - please verify nothing is removed or the content altered. You might also notice some errors. I see the string `common:learn.more` just repeats the same value for its string and this is a visible issue in the UI:

image

Would you mind fixing that one up as well? It should just say "Learn more" and there is already an entry in the translation file for it. Thanks.

**Comment by ellajuengst** [comment]
#1126

**Comment by ellajuengst** [comment]
#1127

**Review by KevinFCormier — APPROVED** [review]
Changes addressed in other PRs.

**Pull request merged**
