### PR TITLE
ACM-2297: update headers/wording/typo on create AWS hosted cluster screen

### PR DESCRIPTION
**Pull request by dtthuynh**
Signed-off-by: David Huynh <dhuynh@redhat.com>
For https://issues.redhat.com/browse/ACM-2297

Fixes:
- Headers can use improved wording, need to capitalize usage of Hosted Control Plane and Hosted Clusters
- typo: "--secret-screds $SECRET_CREDS"
- Copy command copies command using `hypershift`, should be using `oc hcp`
- "Download and install hosted control plane CLI."
should be "Download and install the hosted control plane CLI."
- "Use existing AWS credentials, or create new AWS credentials."
should be "Use your existing AWS credentials, or create new AWS credentials."
- "Click here for Credentials wizard"
should be "Click here for the Credentials wizard"

### CODE REVIEW

**Comment by chenz4027** [comment]
LGTM in general, but looping Brandi to confirm @swopebe 
Hey Brandi, it's mostly the text changes for Hypershift Command wizard. Could you help take a look once you have some spare time? Thanks!

**Review by fxiang1 — APPROVED** [review]
LGTM! Thanks David! we can wait to see if Brandi has any feedback.

**Review by swopebe — APPROVED** [review]
looks great

**Comment by dtthuynh** [comment]
Recreated PR https://github.com/stolostron/console/pull/2385

**Pull request closed without merging**
