### PR TITLE
Update HELM chart repositories table columns

### PR DESCRIPTION
**Pull request by jtomasek**
Signed-off-by: Jiri Tomasek <jtomasek@redhat.com>

### CODE REVIEW

**Comment by KevinFCormier** [comment]
@jtomasek There is a 70% coverage requirement on new code now. You are almost there with 68.1%.

**Comment by jtomasek** [comment]
@KevinFCormier right, occasionally the tests fail on unrelated test with 'noUnusedMocks' for some reason: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stolostron_console/2080/pull-ci-stolostron-console-main-lint-check-unittests-sonarcloud/1575483395339718656

**Comment by KevinFCormier** [comment]
@jtomasek Thanks for pointing that out. I had not seen that issue before.

**Pull request merged**
