### PR TITLE
Add testids for onboarding modal

### PR DESCRIPTION
**Pull request by dtthuynh**
Signed-off-by: David Huynh <dhuynh@redhat.com>

The new onboarding modal doesn't have id nor any predictable testid to grab the element in our test automation. In order to reduce test flake and improve usability we should set these values.

### CODE REVIEW

**Review by fxiang1 — APPROVED** [review]
LGTM! Thanks David!

**Comment by fxiang1** [comment]
@dtthuynh Looks like OnboardingModal.test.tsx failed.

Some hints for running locally:
`DEBUG_PRINT_LIMIT=100000 npm run jest OnboardingModal.test.tsx -- --coverage --collectCoverageFrom=src/routes/Infrastructure/Clusters/ManagedClusters/components/OnboardingModal.tsx`

You can add `screen.debug()` in the test to print the generated HTML.

**Comment by dtthuynh** [comment]
looks like data-* fields are not supported by PatternFly's modal:
https://github.com/patternfly/patternfly-react/blob/main/packages/react-core/src/components/Modal/Modal.tsx

**Review by fxiang1 — APPROVED** [review]
LGTM

**Pull request merged**
