### PR TITLE
Add newlines when needed for description in details page

### PR DESCRIPTION
**Pull request by willkutler**
ref: https://issues.redhat.com/browse/ACM-4728?filter=-1

### CODE REVIEW

**Review by dhaiducek — DISMISSED** [review]

**Comment by mprahl** [comment]
@KevinFCormier @RobDolares @jeswanke @Randy424 could one of you please merge this PR? The unit test failure is not related to this change.

**Comment by Randy424** [comment]
@mprahl I believe @KevinFCormier is the only one among us with override permission. He's out today for the Canadian holiday.

**Review by dhaiducek — APPROVED** [review]

**Pull request merged**
