### PR TITLE
ACM-2758

### PR DESCRIPTION
**Pull request by chenz4027**
https://issues.redhat.com/browse/ACM-2758

image

image

image
image

### CODE REVIEW

**Comment by fxiang1** [comment]
@chenz4027 Just a question about the cards, the design https://marvelapp.com/prototype/1920h2h9/screen/90598599 has this:
image

Did we change it at the last minute?

**Comment by chenz4027** [comment]
Yep @fxiang1 I think so, as per latest comment in the Jira

**Comment by fxiang1** [comment]
@chenz4027 Sorry meant to ask your text doesn't match the design. Is it suppose to match?

image

**Review by fxiang1 — APPROVED** [review]
LGTM! Thanks Maggie for completing this!

**Pull request merged**
