### PR TITLE
[2.7] Update assisted UI lib to v2.7.13-cim

### PR DESCRIPTION
**Pull request by mareklibra**
Release notes:
- https://github.com/openshift-assisted/assisted-installer-ui/releases/tag/v2.7.13-cim

### CODE REVIEW

**Comment by mareklibra** [comment]
@KevinFCormier , can we merge this, please?

**Comment by KevinFCormier** [comment]
@mareklibra I believe 2.7 is still in code freeze. So this would be up to @crizzo71 and @nelsonjean.

**Comment by nelsonjean** [comment]
Hi @KevinFCormier , @mareklibra , ACM 2.7.7 and MCE 2.2.7 are almost done QE. Can this update be deferred to ACM 2.7.8 / MCE 2.2.8, or is there critical customer impact if we don't include it in 2.7.7 / 2.2.7?

**Comment by mareklibra** [comment]
@KevinFCormier @nelsonjean The change is about https://issues.redhat.com/browse/MGMT-14130

Practically, it's just a forgotten backport, (most probably) already tested in 2.8.
Priority is major.

I do not see many risks in merging it.

**Comment by jelkosz** [comment]
@KevinFCormier I understand 2.7.7 is out. Can this be merged to get it into 2.7.8?

**Pull request merged**
