### PR TITLE
Fix ValidatingAdmisstionPolicyBinding filter in discovered policies

### PR DESCRIPTION
**Pull request by yiraeChristineKim**
- Fix typo in GRC common
- Delete dev log
- VAPB policy not available as filter in discovered policies table
- remove the severity column as well for vapb in ByClusterpag
- Fix that Response Action: Audit is not available as filter in discovered policies table
Ref: https://issues.redhat.com/browse/ACM-15839
Ref: https://issues.redhat.com/browse/ACM-15834
Signed-off-by: yiraeChristineKim <yikim@redhat.com>

### CODE REVIEW

**Comment by mprahl** [comment]
@yiraeChristineKim could you please add tests?

**Comment by yiraeChristineKim** [comment]
> @yiraeChristineKim could you please add tests?

Do you mean https://github.com/stolostron/console/pull/4111?

**Comment by mprahl** [comment]
> > @yiraeChristineKim could you please add tests?
> 
> Do you mean #4111?

I was asking for unit tests for the filters that were missing.

**Review by mprahl — APPROVED** [review]

**Review by mprahl — APPROVED** [review]

**Pull request merged**
