### PR TITLE
Show the same action menu on Poicies and PolicyDetail

### PR DESCRIPTION
**Pull request by yiraeChristineKim**
- Align Checkboxes middle of Policy row
- Refactor getPolicySource
Ref: https://issues.redhat.com/browse/ACM-9322
Signed-off-by: yiraeChristineKim <yikim@redhat.com>

### CODE REVIEW

**Comment by yiraeChristineKim** [comment]
@mprahl @dhaiducek  @JustinKuli @KevinFCormier

**Review by mprahl — APPROVED** [review]

**Pull request merged**
