### PR TITLE
Allow upgrade and channel select for MOS only when ARO

### PR DESCRIPTION
**Pull request by KevinFCormier**
- Disable upgrade and channel select for OSD and ROSA Classic
- Update distribution version to show "ARO" for ARO

Related to https://issues.redhat.com/browse/ACM-10135

image

### CODE REVIEW

**Comment by KevinFCormier** [comment]
Added a hold as I'm waiting for @berenss to confirm if the distribution name "ARO" is OK to use.

**Review by robdolares — APPROVED** [review]
/lgtm

**Comment by berenss** [comment]
Yes, confirmed, LGTM. Please ship it. 🚀

**Pull request merged**
