### PR TITLE
update cluster set table for 23957

### PR DESCRIPTION
**Pull request by jeswanke**
stolostron/backlog#23957
Signed-off-by: John Swanke <jswanke@redhat.com>

### CODE REVIEW

**Review by KevinFCormier — COMMENTED** [review]
Could you please enhance the testing in frontend/src/routes/Infrastructure/Clusters/ClusterSets/ClusterSets.test.tsx by adding a mock global cluster set and then verifying some of the changes that apply only for global?

**Comment by jeswanke** [comment]
ok, now with a test--

also, the global clusterset's checkbox can't be selected for bulk actions:

**Comment by KevinFCormier** [comment]
@jeswanke Thanks for adding the test. Cluster status should include all clusters for `global` set:
image

**Pull request merged**
