### PR TITLE
Remove iam-policy in governence

### PR DESCRIPTION
**Pull request by yiraeChristineKim**
Remove the IAM Policy Controller. Remove the IAM policy templates in the console.

Ref: https://issues.redhat.com/browse/ACM-10859

### CODE REVIEW

**Comment by mprahl** [comment]
@yiraeChristineKim could you also please remove the IAM Policy specific code in `PolicyWizard.tsx`?

**Comment by yiraeChristineKim** [comment]
@mprahl Thanks Matt

**Pull request merged**
