### PR TITLE
Fix message typo

### PR DESCRIPTION
**Pull request by KevinFCormier**
`already upgrade` -> `already upgraded`

### CODE REVIEW

**Comment by fxiang1** [comment]
/lgtm
Putting on hold in case @oafischer has anything.

**Comment by KevinFCormier** [comment]
@fxiang1 This was at Oliver's request, so I'm going to let it merge. Thanks for reviewing.

https://github.com/stolostron/console/pull/4123#discussion_r1880601178

**Review by fxiang1 — APPROVED** [review]

**Pull request merged**
