### PR TITLE
[backplane-2.0] [UI] BMA deprecation followups (#1719) (#1738)

### PR DESCRIPTION
**Pull request by KevinFCormier**
Related to https://bugzilla.redhat.com/show_bug.cgi?id=2091625
Add deprecation label and alert to BMA page

### CODE REVIEW

**Comment by KevinFCormier** [comment]
FYI @jtomasek @ammont82 I forgot to mention that anything that falls under the Infrastructure or Credentials navigation items needs to be delivered to the corresponding backplane-x.y z-stream for the MCE dynamic plugin.

**Review by RobDolares — APPROVED** [review]
/lgtm

**Pull request merged**
