### PR TITLE
ACM-12098: Helper function for export of SubRows and returning CSV safe strings

### PR DESCRIPTION
**Pull request by Randy424**
Related to ACM-12099: Here I'm adding some functionality to the export feature that will make exporting SubRows possible and will make exporting strings with comma's a seamless experience.

**_Merge this commit ahead of the  "Implementation" commits!_**

### CODE REVIEW

**Review by KevinFCormier — CHANGES_REQUESTED** [review]
Just 1 inline comment.

**Comment by Randy424** [comment]
@KevinFCormier I rebased on main, so another review is needed!

**Pull request merged**
