### PR TITLE
Fix cluster status for degraded clusters

### PR DESCRIPTION
**Pull request by fxiang1**
Signed-off-by: Feng Xiang <fxiang@redhat.com>

https://issues.redhat.com/browse/ACM-2027

- Add `degraded` to the list of status to check

### CODE REVIEW

**Comment by fxiang1** [comment]
Since 2.5.5 is code freeze right now. Will wait for 2.5.6.

**Comment by KevinFCormier** [comment]
2.5.6 is now open: https://coreos.slack.com/archives/C0140DCKJ5A/p1669241174060239

**Comment by fxiang1** [comment]
Thanks @KevinFCormier !

**Pull request merged**
