### PR TITLE
posthook error status fix

### PR DESCRIPTION
**Pull request by Randy424**
Signed-off-by: randybrunopiverger <rbrunopi@redhat.com>

### CODE REVIEW

**Comment by Randy424** [comment]
@KevinFCormier Hey by any chance do you recognize this error:

```
[frontend] [jest]   ● AcmCountCard › has zero accessibility defects
[frontend] [jest] 
[frontend] [jest]     Cannot read properties of undefined (reading 'then')
[frontend] [jest] 
[frontend] [jest]       at new ApolloError (node_modules/@apollo/client/errors/index.js:29:28)
[frontend] [jest]       at node_modules/@apollo/client/core/QueryManager.js:611:19
[frontend] [jest]       at both (node_modules/@apollo/client/utilities/observables/asyncMap.js:16:53)
[frontend] [jest]       at node_modules/@apollo/client/utilities/observables/asyncMap.js:9:72
[frontend] [jest]       at Object.then (node_modules/@apollo/client/utilities/observables/asyncMap.js:9:24)
[frontend] [jest]       at Object.error (node_modules/@apollo/client/utilities/observables/asyncMap.js:17:49)
[frontend] [jest]       at notifySubscription (node_modules/zen-observable/lib/Observable.js:140:18)
[frontend] [jest]       at onNotify (node_modules/zen-observable/lib/Observable.js:179:3)
[frontend] [jest]       at SubscriptionObserver.error (node_modules/zen-observable/lib/Observable.js:240:7)
[frontend] [jest]       at node_modules/@apollo/client/utilities/observables/iteration.js:4:68
[frontend] [jest]           at Array.forEach (<anonymous>)
[frontend] [jest]       at iterateObserversSafely (node_modules/@apollo/client/utilities/observables/iteration.js:4:25)
[frontend] [jest]       at Object.error (node_modules/@apollo/client/utilities/observables/Concast.js:36:21)
[frontend] [jest]       at notifySubscription (node_modules/zen-observable/lib/Observable.js:140:18)
[frontend] [jest]       at flushSubscription (node_modules/zen-observable/lib/Observable.js:121:5)
[frontend] [jest]       at node_modules/zen-observable/lib/Observable.js:174:14
[frontend] [jest]       at node_modules/zen-observable/lib/Observable.js:73:7
[frontend] [jest]           at runMicrotasks (<anonymous>)
```
Sonar test results: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stolostron_console/2413/pull-ci-stolostron-console-release-2.6-lint-check-unittests-sonarcloud/1605205680321466368


I haven't been able to reproduce it locally.

**Comment by KevinFCormier** [comment]
@Randy424 I think I've seen it before as an intermittent error. Please try it again.

**Pull request merged**
