### PR TITLE
Use Patterns on AcmDonutChart

### PR DESCRIPTION
**Pull request by ChunxiAlexLuo**
Signed-off-by: Chunxi Luo <chuluo@redhat.com>

https://github.com/stolostron/backlog/issues/26194

Screenshot 2022-11-04 at 3 42 54 PM

### CODE REVIEW

**Comment by ChunxiAlexLuo** [comment]
/cc @KevinFCormier @heyethankim

Let me know any feedback

**Comment by heyethankim** [comment]
@ChunxiAlexLuo 
As I noted in the issue, the intention was to enhance the experience including color blind people. But as you can see below, it doesn't solve the issue and made challenging even for non-color blind users. Let me discuss with @imjoyjean and get back to you. 

Here is the link you could try out the color blindness (choose Red-blind or Green-blind) : 
https://www.color-blindness.com/coblis-color-blindness-simulator/ 
image

**Comment by ChunxiAlexLuo** [comment]
> @ChunxiAlexLuo As I noted in the issue, the intention was to enhance the experience for color blind people. But as you can see below, it doesn't solve the issue and made challenging even for non-color blind users. Let me discuss with @imjoyjean and get back to you.
> 
> Here is the link you could try out the color blindness (choose Red-blind or Green-blind) : https://www.color-blindness.com/coblis-color-blindness-simulator/ image

The above is the default Pattern stylish, let me know if there is any specific UI design on this.

**Comment by ChunxiAlexLuo** [comment]
https://github.com/stolostron/backlog/issues/26194#issuecomment-1317334745

Close as we decide to use other color options rather than Patterns

**Pull request closed without merging**
