### PR TITLE
Add a warning when deleting a policy with shared placements

### PR DESCRIPTION
**Pull request by mprahl**
The first commit clarifies the wording in the delete policy modal .

The second commit adds a warning when deleting a policy with shared placements. When deleting a policy, you can select to delete the placements and placement bindings associated with it. These placements and placement bindings could be used by other policies, so a warning is added for this case so that the user is aware before actually deleting them.

image

Relates:
https://issues.redhat.com/browse/ACM-2412

### CODE REVIEW

**Comment by KevinFCormier** [comment]
Approved. Will leave code review to @willkutler

**Review by willkutler — APPROVED** [review]

**Pull request merged**
